apiVersion: v1
kind: ServiceAccount
metadata:
  name: hh-demo-api-sa
  namespace: hh-demo-api
  annotations:
    # Placeholder annotation for AWS IAM Roles for Service Accounts (IRSA)
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/hh-demo-api-role
